version: "3.9"
services:
  mysql-db:
    image: mysql:8.0
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: unopassword
      MYSQL_DATABASE: OrderDb
      MYSQL_USER: myuser
      MYSQL_PASSWORD: unopassword
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  order-service:
    build: .
    container_name: order-service
    depends_on:
      - mysql-db
    ports:
      - "8080:80"
    environment:
      ConnectionStrings__MySqlConnection: "Server=mysql-db;Port=3306;Database=OrderDb;User=myuser;Password=unopassword;"
      AnalysisServiceUrl: "http://analysisservice:5001"
      NotificationServiceUrl: "http://notificationservice:5002"

volumes:
  db_data:
