apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service-deployment
  namespace: smartorder-backend
  labels:
    app: order-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order-service
  template:
    metadata:
      labels:
        app: order-service
    spec:
      containers:
        - name: order-service-container
          image: advanceduno/orderservice:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080  
            - containerPort: 443   
          envFrom:
            - configMapRef:
                name: order-service-config
            # - secretRef:
            #     name: order-service-secret