apiVersion: v1
kind: Service
metadata:
  name: order-service
  namespace: smartorder-backend
spec:
  selector:
    app: order-service
  ports:
    - port: 80
      targetPort: 8080
      name: http
    - port: 443
      targetPort: 443
      name: https
  type: ClusterIP