apiVersion: v1
kind: Service
metadata:
  name: analysis-service
  namespace: smartorder-backend
spec:
  selector:
    app: analysis-service
  ports:
    - port: 5001
      targetPort: 5001
      name: http
    - port: 442
      targetPort: 442
      name: https
  type: ClusterIP