apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-config
  namespace: smartorder-backend
data:
  MYSQL_DATABASE: "ordersdb"
  MYSQL_HOST: "mysql-service-headless"


kind: Secret
metadata:
  name: mysql-secret
  namespace: smartorder-backend
type: Opaque
data:
  MYSQL_USER: bXl1c2Vy  # Base64 encoded "myuser"
  MYSQL_PASSWORD: bXlwYXNzd29yZA==  # Base64 encoded "mypassword"
  MYSQL_ROOT_PASSWORD: cGFzc3dvcmQ=  # Base64 encoded "password"
