# apiVersion: v1
# kind: Service
# metadata:
#   name: mysql-service-headless
#   namespace: smartorder-backend
# spec:
#   clusterIP: None
#   selector:
#     app: mysql-service
#   ports:
#   - port: 3306
#     targetPort: 3306

---
# ------------------------------------------------
# Service to expose MySQL
# ------------------------------------------------
apiVersion: v1
kind: Service
metadata:
  name: mysql-service
  namespace: smartorder-backend
spec:
  selector:
    app: mysql-server
  ports:
    - port: 3306
      targetPort: 3306
      protocol: TCP
      name: mysql
  type: ClusterIP
